#!/bin/bash

# ci_post_clone.sh - Xcode Cloud post-clone script
# This script runs after Xcode Cloud clones the repository
# It creates the xcconfig files that are gitignored (containing secrets)

set -e

echo "=== Creating xcconfig files for Xcode Cloud ==="

CONFIG_DIR="$CI_PRIMARY_REPOSITORY_PATH/DiningDecider/Config"
mkdir -p "$CONFIG_DIR"

# Create Production.xcconfig from environment variables
# Set API_BASE_URL and API_KEY as environment variables in Xcode Cloud workflow settings
cat > "$CONFIG_DIR/Production.xcconfig" << EOF
// Production Configuration - Generated by Xcode Cloud
// Environment variables are set in Xcode Cloud workflow settings

API_BASE_URL = ${API_BASE_URL:-https://dining-decider-api.jenson-zhao.workers.dev}
API_KEY = ${API_KEY:-}
EOF

# Create Development.xcconfig (same as Production for CI)
cat > "$CONFIG_DIR/Development.xcconfig" << EOF
// Development Configuration - Generated by Xcode Cloud

API_BASE_URL = ${API_BASE_URL:-https://dining-decider-api.jenson-zhao.workers.dev}
API_KEY = ${API_KEY:-}
EOF

echo "=== xcconfig files created ==="
echo "Production.xcconfig contents:"
cat "$CONFIG_DIR/Production.xcconfig"
